[workspace]
authors = ["David W.H. Swenson <dwhs@hyperblazer.net>"]
channels = ["conda-forge"]
name = "ghcontribs"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]
dev = { cmd = "npm run dev", cwd = "ghcontribs-viz" }

[dependencies]
python = ">=3.11"
requests = "*"
pytest = "*"
pytest-cov = "*"
jsonschema-with-format-nongpl = "*"
wheel = "*"
jupyterlab = "*"

# for the visualization
nodejs = "*"

[pypi-dependencies]
ghcontribs = { path = ".", editable = true }
